👷update tag format version

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -30,13 +30,13 @@ jobs:
       id: extract_tag
       run: |
         TAG="${{ github.ref_name }}"
-        if [[ "$TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-          echo "major=v${BASH_REMATCH[1]}" >> $GITHUB_ENV
-          echo "minor=v${BASH_REMATCH[1]}.${BASH_REMATCH[2]}" >> $GITHUB_ENV
+        if [[ "$TAG" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+          echo "major=${BASH_REMATCH[1]}" >> $GITHUB_ENV
+          echo "minor=${BASH_REMATCH[1]}.${BASH_REMATCH[2]}" >> $GITHUB_ENV
           echo "patch=$TAG" >> $GITHUB_ENV
           echo "latest=latest" >> $GITHUB_ENV
         else
-          echo "Error: Tag does not match semantic versioning (vX.Y.Z)" >&2
+          echo "Error: Tag does not match semantic versioning (X.Y.Z)" >&2
           exit 1
         fi
 
